remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Serechoo Stash Index
description: A compilation of all current Stash plugins for easy installation.
