name: Manual Build Site

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu/latest
      options: --privileged

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run build script
        run: |
          chmod +x build_site.sh
          ./build_site.sh _site
